chore: update dependencies
near/near-discovery pull request #1133
Opened 2024-04-19 12:55 UTC by shelegdmitriy

2024-04-22 16:35 UTC, shelegdmitriy commented
At this moment I checked that `idos` works as expected and there is no new errors in the console or at the build stage. Fell free to test it using preview link. I can't login using fast auth though. But this problem occurs in production for me too (see this [comment](https://pagodaplatform.slack.com/archives/C053S7ZHERG/p1713794734984079))

2024-04-22 17:19 UTC, jackson-harris-iii commented on src/components/lib/Toast/styles.ts
Are these actual changes or just linter differences, might have a build error if the linter is opinionated.

2024-04-22 17:22 UTC, jackson-harris-iii approved these changes
A few questions about what looks like changes made based on local linter settings, but if that's not going to be a deploy issue than LTGM

2024-04-22 17:22 UTC, jackson-harris-iii commented on src/components/lib/Tooltip/styles.ts
Are these actual changes or just linter differences, might have a build error if the linter is opinionated.

2024-04-22 17:22 UTC, jackson-harris-iii commented on src/components/sidebar-navigation/styles.ts
Looks like there are some actual changes in this file which look good, but also quite a few linter based changes too.

2024-04-22 20:38 UTC, shelegdmitriy commented on src/components/lib/Toast/styles.ts
These changes are caused after updating the `prettier` module. But the presented changes are not critical, so I think we can allow it. WDYT @jackson-harris-iii? Because it also surprised me

2024-04-22 20:39 UTC, shelegdmitriy commented on src/components/sidebar-navigation/styles.ts
Oh, I missed this one: yes, this changes caused by `pnpm prettier:write` script

2024-04-23 14:14 UTC, charleslavon commented
@shelegdmitriy that's a lot of major version updates to include in a single release. For future consideration, releasing major version updates in separate PRs with their own time to settle in production would facilitate easier debugging should errors occur.

2024-04-23 14:19 UTC, shelegdmitriy commented
Make sense. I could split it in a couple of PR's if you wish.

2024-04-23 14:20 UTC, shelegdmitriy commented
On the other hand we can use the preview link to confirm that everything works fine as it was

2024-04-23 15:50 UTC, calebjacob commented
This definitely makes me pretty nervous to merge. Thanks for taking the time to look into the updates. I'd agree with @charleslavon that we should probably break out these major upgrades over multiple PR's and sprints so we can more easily catch and correlate regressions.

2024-04-23 15:54 UTC, shelegdmitriy commented
I agree with all of you. I apologize for not consulting about this at first place. I'm going to mark this PR as draft and will split it into a couple of PRs

2024-04-23 15:54 UTC, charleslavon requested changes
hey @shelegdmitriy I recommend separating the major version updates into distinct PRs, and consider not including updating dependencies that whose functionality we are not able to test with confidence.

2024-04-23 15:55 UTC, charleslavon commented
All good @shelegdmitriy thanks for taking the initiative here!

2024-04-24 17:16 UTC, shelegdmitriy commented
I'm going to close this PR and open a couple more with all this updates

2024-04-24 17:16 UTC, closed without merging