chore: reduce amount of search categories (Part 2/2)
near/near-discovery pull request #1219
Opened 2024-06-25 17:01 UTC by shelegdmitriy

Like I said in this [PR](https://github.com/near/near-discovery-components/pull/836), we decided to 

> Bring the top navbar back along with search (this is the part 2 on the near-discovery side);

In this PR I brought top bar back along with ProfileDropdown.

Relates to https://github.com/near/near-discovery/issues/1196.

Feel free to ask any questions you have!

2024-06-25 17:34 UTC, calebjacob approved these changes
Looks good!

2024-06-25 18:44 UTC, gagdiez requested changes

2024-06-25 18:44 UTC, gagdiez commented on src/components/layouts/DefaultLayout.tsx
> +        {sidebarLayoutEnabled && <LargeScreenHeader />}
We don't want the top menu back, as it collides with other top menus, such as the one of docs

2024-06-26 08:15 UTC, gagdiez commented
@vanessadespain do we have any alternative to bringing back the top menu?

The problem with having a top menu and a side menu is that we end up with:
- A top menu that is mostly empty, only holding a small user profile picture and a search bar
- The page's content content ends up with less space since there are two menus  
- If the content has a top menu (very likely), we end up with two top menus - one for the dev portal, one for the app being embedded

2024-06-26 15:29 UTC, vanessadespain commented
@gagdiez I think your solution is good to meet those reasons!

As an alternative – if you wanted to keep that top nav for the familiarity ease of finding it. You could have the top nav scroll away when the user scrolls down, and have it pop back in when the user starts to scroll up. However, that doesn't solve the issue of having a double stacked nav when the destination also has a top nav. 

So for those reasons I think the solution you have in place is solid! One caveat that can help discoverability of the bottom-left placement is keeping the number of links in the left nav really refined so that ideally we have a gap of white space above the login/sign-up link. If we're not able to remove some of these links, we could consider collapsing them by bringing in accordion. 

Let me know if you'd like to keep exploring this: how to refine the number of navigation items displayed via design and information architecture.

2024-06-26 17:27 UTC, gagdiez commented
thanks @vanessadespain , and could I ask you about suggestions to bring back the search bar? could we put it right above the user profile, and thus also separated from the navigation menu?

Should we put is as a bar? as a button? as a single "magnifying glass" icon?

2024-06-27 19:05 UTC, shelegdmitriy commented
Hey @gagdiez! I've got some inspiration after our meet and I made some changes to put the search into the sidebar and remove top bar and here is a demo I have https://www.loom.com/share/6f027b69d5884da998c6be04cc674c86?sid=88f88850-3204-4e39-9472-c3f9940ed838.

Feel free to ask any questions you have!

cc @charleslavon @vanessadespain

2024-06-28 16:56 UTC, charleslavon commented on src/components/sidebar-navigation/Search.tsx
> +          placeholder: 'Search for apps...',
`Search...`

2024-06-28 16:56 UTC, charleslavon approved these changes

2024-06-28 18:53 UTC, merged