fix: adjust styles for form to scroll on select other on motivation page
near/near-discovery pull request #1260
Opened 2024-07-20 06:00 UTC by jackson-harris-iii

PR address issues in the developer survery:

- ensuring the next button is visible/scrollable when the other input box is displayed 

Closes #1258

2024-07-21 14:58 UTC, charleslavon approved these changes
👍🏾 👍🏾

2024-07-22 15:43 UTC, shelegdmitriy requested changes

2024-07-22 15:43 UTC, shelegdmitriy commented on src/components/research-form-wizard/FormPages/Motivation.tsx
> +import { use, useEffect, useRef, useState } from 'react';
Seems like we don't need `use here`:

```suggestion
import { useEffect, useRef, useState } from 'react';
```

2024-07-23 18:17 UTC, jackson-harris-iii commented
Made an update to this address the rudderstack nested object issue discussed [here](https://github.com/near/near-discovery/issues/1258#issuecomment-2245937717)

2024-07-23 18:37 UTC, shelegdmitriy commented
Hey @jackson-harris-iii take a look at this [video](https://www.loom.com/share/6d935552af6d487384f0fc6437e325a0?sid=f470a953-a411-4d98-9c3f-70df0a701022) please because I'm not sure about the last step on form when I select **"No thanks"** and I can't submit the form

2024-07-23 21:01 UTC, jackson-harris-iii commented
> Hey @jackson-harris-iii take a look at this [video](https://www.loom.com/share/6d935552af6d487384f0fc6437e325a0?sid=f470a953-a411-4d98-9c3f-70df0a701022) please because I'm not sure about the last step on form when I select **"No thanks"** and I can't submit the form

Good catch, a fix has been put in [commit](https://github.com/near/near-discovery/pull/1260/commits/4e6f6d2c7c5106283bc325e70f274380dadfa88f)

2024-07-23 21:29 UTC, shelegdmitriy approved these changes
LGTM!

2024-07-23 21:29 UTC, merged