chore: remove segment
near/near-discovery pull request #338
Opened 2023-08-09 18:20 UTC by roshaans

This PR removes Segment as a dependency.

2023-08-14 11:08 UTC, shelegdmitriy requested changes

2023-08-14 14:23 UTC, mpeterdev commented on src/utils/analytics.ts
> +  const rudderAnalyticsKey = networkId === 'testnet' ? '2R7K9phhzpFzk2zFIq2EFBtJ8BM' : '2R7K9phhzpFzk2zFIq2EFBtJ8BM';
yep, this would definitely be better. No preference on whether this change occurs before merge or if we spin off a new ticket for it

2023-08-29 21:33 UTC, roshaans commented on src/utils/analytics.ts
> +  const rudderAnalyticsKey = networkId === 'testnet' ? '2R7K9phhzpFzk2zFIq2EFBtJ8BM' : '2R7K9phhzpFzk2zFIq2EFBtJ8BM';
Good idea. Lets do this in another ticket

2023-08-30 13:56 UTC, roshaans commented on src/utils/analytics.ts
> +  const rudderAnalyticsKey = networkId === 'testnet' ? '2R7K9phhzpFzk2zFIq2EFBtJ8BM' : '2R7K9phhzpFzk2zFIq2EFBtJ8BM';
Sweet. It is here here: https://pagodaplatform.atlassian.net/browse/SRCH-213

2023-08-30 13:57 UTC, merged