Fix forked component state
near/near-discovery pull request #358
Opened 2023-09-06 16:04 UTC by shelegdmitriy

Closes #348

2023-09-06 16:33 UTC, calebjacob commented
I'm not super familiar with the sandbox editor code, so I'll let @marcinbodnar be the one to approve this one. :)

2023-09-06 16:35 UTC, marcinbodnar requested changes
@shelegdmitriy It seems like it doesn't solve the problem, try refreshing the page.

I can take this issue from you, it's a bit problematic, and I think I was fixing the same issue a few months ago.

2023-09-06 16:37 UTC, shelegdmitriy commented
I actually tried and it was working

2023-09-06 16:37 UTC, shelegdmitriy commented
Have you tried to run my branch locally?

2023-09-06 16:38 UTC, marcinbodnar commented
@shelegdmitriy I tried on the preview.

2023-09-08 12:46 UTC, shelegdmitriy commented on src/components/sandbox/Sandbox.js
> +  // possibly unused
It seems this section below is unused @marcinbodnar could you confirm that?

2023-09-08 16:33 UTC, calebjacob commented
@shelegdmitriy Both preview links seem to work for me.

2023-09-08 16:34 UTC, calebjacob approved these changes

2023-09-08 16:57 UTC, marcinbodnar approved these changes
There is an issue with the red dot that indicates if there are any changes made to the component. It doesn't disappear after you undo the changes made.

We can merge it but the issue should be addressed in a separate PR cc @charleslavon

2023-09-08 17:00 UTC, shelegdmitriy commented
@marcinbodnar good catch! That should be fixed for sure but in a separate PR because it's very minor issue

2023-09-08 17:06 UTC, merged