Notifications - show Notifications Alert with basic conditions
near/near-discovery pull request #403
Opened 2023-09-13 15:21 UTC by marcinbodnar

2023-09-13 16:37 UTC, marcinbodnar commented
@shelegdmitriy This is the modal component after small changes:
https://github.com/near/near-discovery-components/pull/324

2023-09-14 13:03 UTC, shelegdmitriy approved these changes

2023-09-14 15:40 UTC, shelegdmitriy requested changes

2023-09-14 15:40 UTC, shelegdmitriy commented on src/pages/index.tsx
> +          src="near/widget/NearOrg.Notifications.NotificationAlert"
After #408 done we need to update this string:
```suggestion
          src={components.nearOrg.notifications.notificationAlert}
```

2023-09-18 16:24 UTC, milenakrawczyk approved these changes

2023-09-18 18:38 UTC, shelegdmitriy commented on src/pages/index.tsx
> +            setNotificationsSessionStorage,
To close this modal by pressing `esc` add this line:
```suggestion
            setNotificationsSessionStorage,
            onOpenChange: () => setShowNotificationModalState(false),
```

2023-09-18 18:38 UTC, shelegdmitriy approved these changes
LGTM

2023-09-18 18:50 UTC, merged